# Generated by Django 4.2.3 on 2023-10-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretariat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="outline_uuid",
            field=models.CharField(default="not a valid uuid", max_length=25),
            preserve_default=False,
        ),
    ]
