# Generated by Django 4.2.3 on 2023-10-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretariat", "0002_user_outline_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="outline_uuid",
            field=models.CharField(default=None, max_length=36, null=True),
        ),
    ]
