# Generated by Django 4.2.3 on 2023-11-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretariat", "0005_organisation_alter_user_outline_uuid_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
