# Generated by Django 4.2.3 on 2023-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretariat", "0005_organisation_alter_user_outline_uuid_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="outline_group_uuid",
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="outline_uuid",
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
