# Generated by Django 4.2.7 on 2023-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretariat", "0006_alter_organisation_outline_group_uuid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "estimé·e collègue",
                "verbose_name_plural": "estimé·e·s collègues",
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="start_must_be_before_end",
            ),
        ),
    ]
