# Generated by Django 4.2.7 on 2023-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretariat", "0007_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(max_length=70),
        ),
    ]
